// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOVnLplA7HFNulzXGrn_IO88pwu6fNjUo',
    appId: '1:858473103026:web:85f84f38835cc7b3d553ab',
    messagingSenderId: '858473103026',
    projectId: 'smartcare-3bd72',
    authDomain: 'smartcare-3bd72.firebaseapp.com',
    storageBucket: 'smartcare-3bd72.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOVnLplA7HFNulzXGrn_IO88pwu6fNjUo',
    appId: '1:858473103026:android:85f84f38835cc7b3d553ab',
    messagingSenderId: '858473103026',
    projectId: 'smartcare-3bd72',
    authDomain: 'smartcare-3bd72.firebaseapp.com',
    storageBucket: 'smartcare-3bd72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOVnLplA7HFNulzXGrn_IO88pwu6fNjUo',
    appId: '1:858473103026:ios:smartcare',
    messagingSenderId: '858473103026',
    projectId: 'smartcare-3bd72',
    authDomain: 'smartcare-3bd72.firebaseapp.com',
    storageBucket: 'smartcare-3bd72.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );
}
